# Generated by Django 5.2.6 on 2025-09-17 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='target_department',
            field=models.CharField(blank=True, choices=[('IT', 'Công nghệ thông tin'), ('HR', 'Nhân sự'), ('Finance', 'Tài chính'), ('Marketing', 'Marketing'), ('Operations', 'Vận hành')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='target_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility_type',
            field=models.CharField(choices=[('department', 'Phòng ban'), ('specific', 'Người dùng cụ thể')], default='department', max_length=20),
        ),
    ]
