# Generated by Django 5.2.6 on 2025-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_target_department_document_target_users_and_more'),
        ('users', '0003_department_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='target_department',
        ),
        migrations.AddField(
            model_name='document',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='documents', to='users.department'),
        ),
    ]
