# Generated by Django 5.2.6 on 2025-09-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_target_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibility_type',
            field=models.CharField(blank=True, choices=[('department', 'Phòng ban'), ('specific', 'Người dùng cụ thể')], default='department', max_length=20),
        ),
    ]
