# Generated by Django 5.2.6 on 2025-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Công nghệ thông tin'), ('HR', 'Nhân sự'), ('Finance', 'Tài chính'), ('Marketing', 'Marketing'), ('Operations', 'Vận hành')], max_length=100),
        ),
    ]
