# Generated by Django 5.2.6 on 2025-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_admin_and_common_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.department'),
        ),
    ]
