# Generated by Django 5.2.6 on 2025-09-19 15:05

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_multiple_admins(apps, schema_editor):
    Department = apps.get_model('users', 'Department')
    UserProfile = apps.get_model('users', 'UserProfile')
    User = apps.get_model('auth', 'User')

    # Get common department
    common_dept = Department.objects.get(is_common=True)

    # Create admin department if not exists
    admin_dept, created = Department.objects.get_or_create(name='Quản trị', defaults={'is_common': False})

    # Create single admin user
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'is_staff': True,
            'is_superuser': True,
            'password': make_password('admin123')
        }
    )
    if created:
        # Create UserProfile for admin
        user_profile, _ = UserProfile.objects.get_or_create(user=admin_user)
        user_profile.is_admin = True
        user_profile.position = 'Administrator'

        # Add admin to both common and admin departments
        user_profile.departments.add(common_dept)
        user_profile.departments.add(admin_dept)
        user_profile.save()


def reverse_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RunPython(create_multiple_admins, reverse_func),
    ]
