# Generated by Django 5.2.6 on 2025-09-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_created_by'),
        ('users', '0009_update_admin_department_assignment'),
    ]

    operations = [
    ]
